spring.application.name=demo

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/batch_schema?binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
spring.datasource.username=batch_user
spring.datasource.password=batchuser
spring.datasource.driver-class-name=org.postgresql.Driver

# Batch Schema Auto-Creation
spring.sql.init.platform=postgres
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Enable Detailed Logging
# logging.level.org.springframework.jdbc=DEBUG
# logging.level.com.zaxxer.hikari=DEBUG
